### Enable to require TLS decrpytion at pod level, otherwise assumed it's handled at the NLB
service:
  tls:
    enabled: false
    path: /etc/tls
    ### Required (if dispatch.tls.enabled)
    secretName:

dashboard:
  enabled: true
  port: 8080

datastore:
  engine: memory
  connection:
    ### Define either uri or uriSecretName but not both
    uri:
    uriSecretName:
    maxOpenConn: 50
    minOpenConn: 10
  gc:
    interval: 3m0s
    maxOperationTime: 1m0s
    window: 24h0m0s

dispatch:
  enabled: true
  port: 50053

grpc:
  enabled: true
  port: 50051
  ### Define either presharedKey or presharedKeySecretName but not both
  presharedKey:
  presharedKeySecretName:
  maxConnAge: 30s
  network: tcp
  shutdownGracePeriod: 30s

http:
  enabled: true
  port: 8443

metrics:
  enabled: true
  port: 9090
  tls:
    enabled: false
    cert:
    key:

  # disable-v1-schema-api
  # ns-cache-expiration
  # schema-prefixes-required

replicas: 3

image:
  repository: quay.io/authzed/spicedb
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

logLevel: debug
